### ISSUE TITLE
Battle plan

### ISSUE THREAD

**Issue by CallMeArtych** [CallMeArtych/bp-text#2]
- [x] Úvod
  - [x] Cíle práce
  - [x] Co není cílem práce
- [x] Rešerše existujicích řešení
  - [x] Na co se zaměřit
  - [x] Datawatch Monarch
  - [x] SiMX TextConverter
  - [x] OpenRefine
  - [x] Parse-O-Matic
  - [x] Shrnuti
- [ ] Analyza použitelných knihoven
  - [x] Specifikace vstupních souborů
    - [x] Rozbor a požadavky
    - [x] Microsoft.Extensions.FileSystemGlobbing
    - [x] Glob.cs
    - [x] DotNet.Glob
    - [x] Minimatch
    - [x] Závěr
  - [x] Extrakce dat z polustrukturovaných textů
    - [x] Rozbor a požadavky
    - [ ] Škala složitostí (Regex ---- Lexer/Generatory gramatik)
    - [x] Template (Perl)
    - [x] TemplateMaker (Python)
    - [x] Reparse (Python)
    - [x] TextFSM (Python)
    - [x] Spusteni Pythonu přimo z .NETu anebo IronPython
    - [x] Závěr
  - [x] Transformace extrahovaných dat (XSLT)
    - [x] Popsat strukturovane formaty
    - [x] XSLT
    - [x] JSON to JSON
  - [ ] Generování přehledného výstupu (HTML, graf)
  - [ ] Plánování extrakcí
    - [x] Hangfire
    - [ ] Quartz.NET
    - [ ] Windows Task Sheduler
  - [ ] Spuštění extrakce pod jiným uživatelem a ukládaní přihlašovácích údajů
- [ ] Návrh
  - [ ] Rozdělení aplikace na vrstvy
  - [ ] Spuštění Python kódu z .NET aplikace (IronPython)
  - [ ] Něco dalšiho
- [ ] Testování
- [ ] Závěr

**Comment by CallMeArtych** [comment]
Mučení dávno skončilo, bakalářka byla úspěšně odevzdána.

**Comment by francma** [comment]
:C
